LPD-97689 Replace poi-ooxml-lite dependency with poi-ooxml-full
This is to resolve `NoClassDefFoundError` when processing OOXML Word documents. Tika 3.x's OOXML Word extractor now requires `com.microsoft.schemas.vml.impl.CTShapeImpl` whenever a document contains an embedded object. The poi-ooxml-lite dependency omits the required Microsoft classes.