LPD-97689 Provide a newer jsoup version for the portal-tika module
The tika-parser-html-module dependencey requires a newer version of jsoup for Tika 3.3.1. Using the com.liferay.shared.dependencies.jsoup version of jsoup results in NoClassDefFoundError errors when HTML is parsed and bumping the com.liferay.shared.dependencies.jsoup version is too risky given how many modules use it and the past performance issues Liferay has had.