LPS-163136 Update jasperreports and dependecies to 6.20.0
Update required in order to resolve failing tests for
portal-reports-engine-console-jasper-test.

Error:
java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()