LPS-154947 SystemProperties: Depend on 'com.liferay.petra.io' to fix 'java.lang.NoClassDefFoundError: com/liferay/petra/io/unsync/UnsyncStringReader'(Task :apps:analytics:analytics-dxp-entity-rest-impl:buildREST)